CREATE TABLE [dbo].[FLITMSUB] (
    [IINMBR]       DECIMAL (6)    NULL,
    [IIDGRT]       CHAR (2)       NULL,
    [IIMINO]       DECIMAL (7, 2) NULL,
    [IIHAZM]       CHAR (1)       NULL,
    [IISPYN]       CHAR (1)       NULL,
    [IISMFG]       CHAR (4)       NULL,
    [IIFORM]       CHAR (1)       NULL,
    [IILMTU]       DECIMAL (7)    NULL,
    [IILMTP]       DECIMAL (5, 4) NULL,
    [IIADSC]       CHAR (20)      NULL,
    [IIHZMX]       DECIMAL (6)    NULL,
    [IISHDT]       CHAR (9)       NULL,
    [IIOVCG]       CHAR (2)       NULL,
    [IIPLCT]       DECIMAL (7, 2) NULL,
    [IICNTP]       CHAR (2)       NULL,
    [IIDOSE]       DECIMAL (5)    NULL,
    [IIMDL]        DECIMAL (7)    NULL,
    [IIVCTX]       DECIMAL (5, 2) NULL,
    [IIFGEL]       CHAR (1)       NULL,
    [IIBDNM]       CHAR (25)      NULL,
    [IICCFQ]       CHAR (2)       NULL,
    [IICHFM]       CHAR (1)       NULL,
    [IIACFM]       CHAR (1)       NULL,
    [IIORET]       CHAR (1)       NULL,
    [IIMFCN]       CHAR (10)      NULL,
    [IISLBN]       CHAR (1)       NULL,
    [IIMNQT]       DECIMAL (5)    NULL,
    [IICNTY]       CHAR (2)       NULL,
    [IISDRT]       CHAR (1)       NULL,
    [IIRSRV]       CHAR (1)       NULL,
    [IIRGFM]       CHAR (1)       NULL,
    [IIONFM]       CHAR (1)       NULL,
    [IIWKEY]       CHAR (1)       NULL,
    [IIGTIN]       CHAR (14)      NULL,
    [IILNAM]       CHAR (30)      NULL,
    [IISPLM]       DECIMAL (1)    NULL,
    [IISPLA]       DECIMAL (1)    NULL,
    [IIMCRD]       DECIMAL (3, 1) NULL,
    [IITOPP]       CHAR (1)       NULL,
    [IIPCNM]       CHAR (25)      NULL,
    [IISPEC]       CHAR (1)       NULL,
    [IIIMS]        CHAR (1)       NULL,
    [IICONT]       CHAR (1)       NULL,
    [I@SPRT]       CHAR (1)       NULL,
    [IIOVRLMT]     CHAR (1)       NULL,
    [IIAITEM1]     DECIMAL (6)    NULL,
    [IIAITEM2]     DECIMAL (6)    NULL,
    [IIFLAG1]      CHAR (1)       NULL,
    [IIFLAG2]      CHAR (1)       NULL,
    [IIMDOH]       DECIMAL (3)    NULL,
    [IIPRLK]       CHAR (1)       NULL,
    [IICATG]       CHAR (10)      NULL,
    [IISEG1]       CHAR (3)       NULL,
    [IISEG2]       CHAR (3)       NULL,
    [IINORW]       CHAR (1)       NULL,
    [FLITMSUB_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FLITMSUB_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FLITMSUB] PRIMARY KEY NONCLUSTERED ([FLITMSUB_key] ASC)
);


GO
CREATE CLUSTERED INDEX [FLITMSUB_IX_clustered]
    ON [dbo].[FLITMSUB]([IINMBR] ASC);

