CREATE TABLE [dbo].[FPCUSMAS] (
    [CNUMBR]       DECIMAL (6)    NULL,
    [CLNAME]       CHAR (30)      NULL,
    [CAHEAD]       CHAR (30)      NULL,
    [CSTRET]       CHAR (30)      NULL,
    [CCTOWN]       CHAR (20)      NULL,
    [CSTATE]       CHAR (2)       NULL,
    [CZIP]         CHAR (9)       NULL,
    [CSALSR]       CHAR (30)      NULL,
    [CSRNAM]       CHAR (30)      NULL,
    [CSRCTN]       CHAR (20)      NULL,
    [CSMAIL]       CHAR (1)       NULL,
    [CCTYCD]       DECIMAL (2)    NULL,
    [CCNTRY]       CHAR (10)      NULL,
    [CCONTY]       CHAR (3)       NULL,
    [CTERRY]       CHAR (3)       NULL,
    [CREGN]        CHAR (2)       NULL,
    [CSTUS]        CHAR (1)       NULL,
    [CCRSTS]       CHAR (1)       NULL,
    [CCHIER]       CHAR (4)       NULL,
    [CBILTO]       DECIMAL (6)    NULL,
    [CSLTX#]       CHAR (10)      NULL,
    [CSTEXP]       DECIMAL (7)    NULL,
    [CSINST]       CHAR (60)      NULL,
    [CSRRTN]       DECIMAL (2)    NULL,
    [CSARTL]       DECIMAL (6)    NULL,
    [CLPCD]        CHAR (1)       NULL,
    [CLPPCT]       DECIMAL (5, 4) NULL,
    [CLPDFT]       CHAR (1)       NULL,
    [CLDFTP]       DECIMAL (5, 4) NULL,
    [CLDFTA]       CHAR (1)       NULL,
    [CSPCD]        DECIMAL (1)    NULL,
    [CCPDSC]       DECIMAL (5, 4) NULL,
    [CPMCD]        CHAR (10)      NULL,
    [CSACST]       DECIMAL (6)    NULL,
    [CSCRLM]       DECIMAL (7)    NULL,
    [CSPORQ]       CHAR (1)       NULL,
    [CSDSAC]       DECIMAL (3, 3) NULL,
    [CSTXEM]       CHAR (1)       NULL,
    [CSBACK]       CHAR (1)       NULL,
    [CCOMDF]       CHAR (1)       NULL,
    [CSSPLT]       CHAR (1)       NULL,
    [CSISEQ]       CHAR (1)       NULL,
    [CSACCD]       DECIMAL (6)    NULL,
    [CSBLST]       CHAR (1)       NULL,
    [CSSPEC]       CHAR (1)       NULL,
    [CSBEST]       CHAR (1)       NULL,
    [CSMNDV]       CHAR (25)      NULL,
    [CSIVDP]       CHAR (25)      NULL,
    [CSCHDP]       CHAR (25)      NULL,
    [CSLSMN]       DECIMAL (4)    NULL,
    [CSCMDP]       DECIMAL (5, 3) NULL,
    [CSADD$]       DECIMAL (7, 2) NULL,
    [CSTREG]       CHAR (10)      NULL,
    [CSREXP]       DECIMAL (7)    NULL,
    [CDEA#]        CHAR (9)       NULL,
    [CDEEXP]       DECIMAL (7)    NULL,
    [CSHIN#]       CHAR (9)       NULL,
    [CLAB1]        CHAR (8)       NULL,
    [CLAB2]        CHAR (8)       NULL,
    [CSTXT1]       CHAR (30)      NULL,
    [CSTXT2]       CHAR (30)      NULL,
    [CSTXT3]       CHAR (30)      NULL,
    [CSPHNA]       DECIMAL (3)    NULL,
    [CSPHNE]       DECIMAL (3)    NULL,
    [CSPHNN]       DECIMAL (4)    NULL,
    [CSFAXA]       DECIMAL (3)    NULL,
    [CSFAXE]       DECIMAL (3)    NULL,
    [CSFAXN]       DECIMAL (4)    NULL,
    [CSRCNM]       CHAR (9)       NULL,
    [CSRCEX]       DECIMAL (7)    NULL,
    [CSCHLD]       CHAR (20)      NULL,
    [CVLCTY]       CHAR (1)       NULL,
    [CSSTAX]       DECIMAL (2)    NULL,
    [CSLTX1]       DECIMAL (4)    NULL,
    [CSLTX2]       DECIMAL (4)    NULL,
    [CSAUTP]       CHAR (20)      NULL,
    [CSAUEX]       DECIMAL (7)    NULL,
    [CSPSPW]       DECIMAL (2)    NULL,
    [CSCAR#]       DECIMAL (2)    NULL,
    [CSPREF]       CHAR (1)       NULL,
    [CSLADT]       DECIMAL (7)    NULL,
    [CTYPE]        DECIMAL (4)    NULL,
    [CSBSTY]       CHAR (2)       NULL,
    [CSACTY]       CHAR (2)       NULL,
    [CSOMIT]       CHAR (1)       NULL,
    [CBONLY]       CHAR (1)       NULL,
    [C1IOD]        CHAR (1)       NULL,
    [CSPHRM]       CHAR (1)       NULL,
    [C1COD]        CHAR (1)       NULL,
    [CSSUB]        CHAR (1)       NULL,
    [CSRPCK]       CHAR (1)       NULL,
    [CSREST]       CHAR (9)       NULL,
    [CSDUPI]       CHAR (1)       NULL,
    [CSSHPL]       CHAR (1)       NULL,
    [CSPARS]       CHAR (1)       NULL,
    [CSPRCL]       CHAR (1)       NULL,
    [CARGL]        CHAR (24)      NULL,
    [CSCDS#]       CHAR (24)      NULL,
    [CSLBL#]       CHAR (24)      NULL,
    [CSOID#]       CHAR (24)      NULL,
    [CSROE#]       CHAR (24)      NULL,
    [CSSDS#]       CHAR (24)      NULL,
    [CREMIT]       CHAR (2)       NULL,
    [CSANL1]       CHAR (3)       NULL,
    [CSANL2]       CHAR (3)       NULL,
    [CPRAWP]       CHAR (1)       NULL,
    [CMSIFL]       CHAR (1)       NULL,
    [CMSISR]       CHAR (10)      NULL,
    [CSPCOC]       DECIMAL (1)    NULL,
    [CSPDOC]       DECIMAL (5, 4) NULL,
    [CSBLOC]       CHAR (1)       NULL,
    [CSSRX]        CHAR (3)       NULL,
    [CSSOTC]       CHAR (3)       NULL,
    [CSRXSL]       CHAR (3)       NULL,
    [CSOTSL]       CHAR (3)       NULL,
    [CSGNSB]       CHAR (1)       NULL,
    [CSGNPF]       CHAR (1)       NULL,
    [CSGNDS]       CHAR (1)       NULL,
    [CSBOMG]       CHAR (1)       NULL,
    [CSEDI1]       CHAR (1)       NULL,
    [CSEDI2]       CHAR (1)       NULL,
    [CSLSDT]       DECIMAL (7)    NULL,
    [CSOTSC]       CHAR (1)       NULL,
    [CSOTPD]       DECIMAL (8)    NULL,
    [CSRBTC]       CHAR (1)       NULL,
    [CSSPDM]       CHAR (1)       NULL,
    [CSEDII]       CHAR (1)       NULL,
    [CSEDIP]       CHAR (1)       NULL,
    [CSCONF]       CHAR (1)       NULL,
    [CSCFDT]       DECIMAL (7)    NULL,
    [CSMXLB]       DECIMAL (5)    NULL,
    [CSMGRM]       DECIMAL (7)    NULL,
    [CSSGRM]       DECIMAL (7)    NULL,
    [FPCUSMAS_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FPCUSMAS_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FPCUSMAS] PRIMARY KEY NONCLUSTERED ([FPCUSMAS_key] ASC)
);


GO
CREATE CLUSTERED INDEX [FPCUSMAS_IX_clustered]
    ON [dbo].[FPCUSMAS]([CNUMBR] ASC);

