CREATE TABLE [dbo].[FPCUSSB2] (
    [C2NMBR]       DECIMAL (6)    NULL,
    [C2SHWS]       DECIMAL (2)    NULL,
    [C2SHW2]       DECIMAL (2)    NULL,
    [C2SHW3]       DECIMAL (2)    NULL,
    [C2TCLS]       CHAR (5)       NULL,
    [C2BGRP]       CHAR (5)       NULL,
    [C2BGID]       CHAR (10)      NULL,
    [C2CHID]       CHAR (5)       NULL,
    [C2CSID]       CHAR (10)      NULL,
    [C2SATD]       CHAR (1)       NULL,
    [C2MEID]       CHAR (11)      NULL,
    [C2TERR]       CHAR (5)       NULL,
    [C2PDEC]       DECIMAL (3)    NULL,
    [C2PSLS]       DECIMAL (4)    NULL,
    [C2ADSC]       CHAR (1)       NULL,
    [C2VIP#]       DECIMAL (6)    NULL,
    [C2SISC]       DECIMAL (6)    NULL,
    [C2ABC]        CHAR (1)       NULL,
    [C2PDSC]       CHAR (1)       NULL,
    [C2AFFL]       DECIMAL (6)    NULL,
    [C2DOVR]       CHAR (1)       NULL,
    [C2SOVR]       CHAR (1)       NULL,
    [C2SCPD]       DECIMAL (7)    NULL,
    [C2SPCR]       CHAR (1)       NULL,
    [C2EDG1]       CHAR (35)      NULL,
    [C2EDG2]       CHAR (4)       NULL,
    [C2NAME]       CHAR (20)      NULL,
    [C2OTCS]       DECIMAL (4)    NULL,
    [C2REBT]       CHAR (2)       NULL,
    [C2FAXS]       CHAR (1)       NULL,
    [C2MFOP]       DECIMAL (4)    NULL,
    [C2MFCL]       DECIMAL (4)    NULL,
    [C2SAOP]       DECIMAL (4)    NULL,
    [C2SACL]       DECIMAL (4)    NULL,
    [C2APH1]       CHAR (10)      NULL,
    [C2APH2]       CHAR (10)      NULL,
    [C2MDLO]       DECIMAL (4)    NULL,
    [C2FRTP]       DECIMAL (4, 4) NULL,
    [C2CATG]       CHAR (1)       NULL,
    [C2CDSC]       CHAR (1)       NULL,
    [C2CPDY]       DECIMAL (2)    NULL,
    [C2FPED]       CHAR (1)       NULL,
    [C2FGVL]       DECIMAL (7)    NULL,
    [C2FGPC]       DECIMAL (4, 2) NULL,
    [C2RMID]       DECIMAL (15)   NULL,
    [C2HAY#]       CHAR (7)       NULL,
    [C2DEA#]       CHAR (9)       NULL,
    [C2DEEX]       DECIMAL (7)    NULL,
    [C2RBCK]       CHAR (1)       NULL,
    [C2RCAC]       DECIMAL (6)    NULL,
    [C2BYCR]       CHAR (1)       NULL,
    [C2TCLT]       CHAR (5)       NULL,
    [C2QTDS]       CHAR (1)       NULL,
    [C2FXSC]       CHAR (2)       NULL,
    [C2PVID]       DECIMAL (7)    NULL,
    [C2340B]       CHAR (20)      NULL,
    [C2GPO]        CHAR (3)       NULL,
    [C2INCC]       CHAR (1)       NULL,
    [C2ISAC]       DECIMAL (6)    NULL,
    [C2EXAC]       CHAR (7)       NULL,
    [C2PDAM]       DECIMAL (9)    NULL,
    [C2NPI]        DECIMAL (10)   NULL,
    [C2GLN]        CHAR (13)      NULL,
    [C2PRAS]       CHAR (1)       NULL,
    [C2ACSF]       CHAR (1)       NULL,
    [C2CTCL]       CHAR (1)       NULL,
    [C2QEST]       CHAR (1)       NULL,
    [C2QDAT]       DECIMAL (7)    NULL,
    [C2FXSD]       CHAR (1)       NULL,
    [C2RFXA]       DECIMAL (3)    NULL,
    [C2RFXE]       DECIMAL (3)    NULL,
    [C2RFXN]       DECIMAL (4)    NULL,
    [C2STRG]       CHAR (10)      NULL,
    [C2SREX]       DECIMAL (7)    NULL,
    [C2SITC]       CHAR (2)       NULL,
    [C2WEBST]      CHAR (50)      NULL,
    [C2CTFG]       CHAR (1)       NULL,
    [C2CTDT]       DECIMAL (7)    NULL,
    [C2DSFG]       CHAR (1)       NULL,
    [C2DSDT]       DECIMAL (7)    NULL,
    [C2STYP]       DECIMAL (4)    NULL,
    [C2OLDT]       DECIMAL (7)    NULL,
    [C2SHC1]       DECIMAL (2)    NULL,
    [C2SHC2]       DECIMAL (2)    NULL,
    [C2SHC3]       DECIMAL (2)    NULL,
    [C2RCEM]       CHAR (40)      NULL,
    [C2RCPF]       CHAR (1)       NULL,
    [C2DTE1]       DECIMAL (7)    NULL,
    [C2DTE3]       DECIMAL (7)    NULL,
    [C21BK1]       CHAR (1)       NULL,
    [C21BK2]       CHAR (1)       NULL,
    [C21BK3]       CHAR (1)       NULL,
    [C22BK1]       CHAR (2)       NULL,
    [C22BK2]       CHAR (2)       NULL,
    [C22BK3]       CHAR (2)       NULL,
    [C23BK1]       CHAR (3)       NULL,
    [C23BK2]       CHAR (3)       NULL,
    [C23BK3]       CHAR (3)       NULL,
    [C24BK1]       CHAR (4)       NULL,
    [C24BK2]       CHAR (4)       NULL,
    [C24BK3]       CHAR (4)       NULL,
    [C26NM1]       DECIMAL (6)    NULL,
    [C26NM2]       DECIMAL (6)    NULL,
    [C26NM3]       DECIMAL (6)    NULL,
    [C2FID]        CHAR (12)      NULL,
    [FPCUSSB2_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FPCUSSB2_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FPCUSSB2] PRIMARY KEY NONCLUSTERED ([FPCUSSB2_key] ASC)
);


GO
CREATE CLUSTERED INDEX [FPCUSSB2_IX_clustered]
    ON [dbo].[FPCUSSB2]([C2NMBR] ASC, [C2SHWS] ASC, [C2SHW2] ASC, [C2SHW3] ASC);

