CREATE TABLE [dbo].[FPITWREC] (
    [IWDATE]    DECIMAL (7)    NULL,
    [IWTIME]    DECIMAL (6)    NULL,
    [IWITEM]    DECIMAL (6)    NULL,
    [IWTYPE]    CHAR (1)       NULL,
    [IWLOC]     DECIMAL (2)    NULL,
    [IWZONE]    CHAR (2)       NULL,
    [IWAISL]    CHAR (2)       NULL,
    [IWBAY]     CHAR (2)       NULL,
    [IWTIER]    CHAR (1)       NULL,
    [IWBIN]     CHAR (2)       NULL,
    [IWOLOC]    DECIMAL (2)    NULL,
    [IWFLOC]    DECIMAL (2)    NULL,
    [IWORD#]    DECIMAL (7)    NULL,
    [IWSEQ#]    DECIMAL (4)    NULL,
    [IWAAC]     DECIMAL (7, 2) NULL,
    [IWSRC]     DECIMAL (7, 2) NULL,
    [IWAWC]     DECIMAL (7, 2) NULL,
    [IWCRUP]    DECIMAL (7, 2) NULL,
    [IWVEXP]    DECIMAL (7)    NULL,
    [IWRCOD]    CHAR (1)       NULL,
    [IWSTAT]    CHAR (1)       NULL,
    [IWOQTY]    DECIMAL (7)    NULL,
    [IWRQTY]    DECIMAL (7)    NULL,
    [IWVEND]    DECIMAL (5)    NULL,
    [IWBUYR]    DECIMAL (3)    NULL,
    [IWATYP]    CHAR (1)       NULL,
    [IWDSPY]    CHAR (1)       NULL,
    [IWORDT]    DECIMAL (7)    NULL,
    [IWITAF]    CHAR (1)       NULL,
    [IWPDSF]    CHAR (1)       NULL,
    [IWLOT#]    CHAR (15)      NULL,
    [IWEDAT]    DECIMAL (7)    NULL,
    [IWMTCS]    DECIMAL (7, 2) NULL,
    [IWLBCS]    DECIMAL (7, 2) NULL,
    [IWFBCS]    DECIMAL (7, 2) NULL,
    [IWVBCS]    DECIMAL (7, 2) NULL,
    [IWICCS]    DECIMAL (7, 2) NULL,
    [IWINAC]    CHAR (24)      NULL,
    [IWCLAC]    CHAR (24)      NULL,
    [IWCRD#]    DECIMAL (7)    NULL,
    [IWLTD]     CHAR (1)       NULL,
    [IWRECA]    CHAR (2)       NULL,
    [IWFGPC]    DECIMAL (5, 4) NULL,
    [IWRBTP]    CHAR (2)       NULL,
    [IWFGLN]    CHAR (1)       NULL,
    [load_date] DATETIME       CONSTRAINT [DF_FPITWREC_load_date] DEFAULT (getdate()) NOT NULL
);

