CREATE TABLE [dbo].[FPITMSUB] (
    [I@NMBR]       DECIMAL (6)    NULL,
    [I@DGRT]       CHAR (2)       NULL,
    [I@MINO]       DECIMAL (7, 2) NULL,
    [I@HAZM]       CHAR (1)       NULL,
    [I@SPYN]       CHAR (1)       NULL,
    [I@SMFG]       CHAR (4)       NULL,
    [I@FORM]       CHAR (1)       NULL,
    [I@LMTU]       DECIMAL (7)    NULL,
    [I@LMTP]       DECIMAL (5, 4) NULL,
    [I@ADSC]       CHAR (20)      NULL,
    [I@HZMX]       DECIMAL (6)    NULL,
    [I@SHDT]       CHAR (9)       NULL,
    [I@OVCG]       CHAR (3)       NULL,
    [I@PLCT]       DECIMAL (7, 2) NULL,
    [I@CNTP]       CHAR (2)       NULL,
    [I@DOSE]       DECIMAL (5)    NULL,
    [I@MDL]        DECIMAL (7)    NULL,
    [I@VCTX]       DECIMAL (5, 2) NULL,
    [I@FGEL]       CHAR (1)       NULL,
    [I@BDNM]       CHAR (25)      NULL,
    [I@CCFQ]       CHAR (2)       NULL,
    [I@CHFM]       CHAR (1)       NULL,
    [I@ACFM]       CHAR (1)       NULL,
    [I@ORET]       CHAR (1)       NULL,
    [I@MFCN]       CHAR (10)      NULL,
    [I@SLBN]       CHAR (1)       NULL,
    [I@MNQT]       DECIMAL (5)    NULL,
    [I@CNTY]       CHAR (2)       NULL,
    [I@SDRT]       CHAR (1)       NULL,
    [I@RSRV]       CHAR (1)       NULL,
    [I@RGFM]       CHAR (1)       NULL,
    [I@ONFM]       CHAR (1)       NULL,
    [I@WKEY]       CHAR (1)       NULL,
    [I@GTIN]       CHAR (14)      NULL,
    [I@LNAM]       CHAR (30)      NULL,
    [I@SPLM]       DECIMAL (1)    NULL,
    [I@SPLA]       DECIMAL (1)    NULL,
    [I@MCRD]       DECIMAL (3, 1) NULL,
    [I@TOPP]       CHAR (1)       NULL,
    [I@PCNM]       CHAR (25)      NULL,
    [I@SPEC]       CHAR (1)       NULL,
    [I@IMS]        CHAR (1)       NULL,
    [I@CONT]       CHAR (1)       NULL,
    [I@SPRT]       CHAR (1)       NULL,
    [I@OVRLMT]     CHAR (1)       NULL,
    [I@AITEM1]     DECIMAL (6)    NULL,
    [I@AITEM2]     DECIMAL (6)    NULL,
    [I@FLAG1]      CHAR (1)       NULL,
    [I@FLAG2]      CHAR (1)       NULL,
    [I@MDOH]       DECIMAL (3)    NULL,
    [I@PRLK]       CHAR (1)       NULL,
    [I@CATG]       CHAR (10)      NULL,
    [I@SEG1]       CHAR (3)       NULL,
    [I@SEG2]       CHAR (3)       NULL,
    [I@NORW]       CHAR (1)       NULL,
    [FPITMSUB_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FPITMSUB_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FPITMSUB] PRIMARY KEY NONCLUSTERED ([FPITMSUB_key] ASC)
);


GO
CREATE CLUSTERED INDEX [IX_FPITMSUB]
    ON [dbo].[FPITMSUB]([I@NMBR] ASC);

