CREATE TABLE [dbo].[FPITMMAS] (
    [ITMNUM]       DECIMAL (6)    NULL,
    [ITSTAT]       CHAR (1)       NULL,
    [ITDLD]        DECIMAL (7)    NULL,
    [ITINVT]       CHAR (1)       NULL,
    [ITINVC]       CHAR (1)       NULL,
    [ITSPCG]       CHAR (1)       NULL,
    [ITDESC]       CHAR (30)      NULL,
    [ITSDES]       CHAR (30)      NULL,
    [ITQUAL]       CHAR (15)      NULL,
    [ITQULD]       CHAR (15)      NULL,
    [ITGNRC]       CHAR (30)      NULL,
    [ITGNSR]       CHAR (30)      NULL,
    [ITSIZE]       CHAR (5)       NULL,
    [ITFORM]       CHAR (2)       NULL,
    [ITFLNE]       DECIMAL (4)    NULL,
    [ITFLSN]       DECIMAL (3)    NULL,
    [ITVNDN]       DECIMAL (5)    NULL,
    [ITVSUF]       DECIMAL (4)    NULL,
    [ITVNSO]       CHAR (5)       NULL,
    [ITVNSR]       CHAR (30)      NULL,
    [ITYNDC]       CHAR (15)      NULL,
    [ITNWTT]       CHAR (1)       NULL,
    [ITNLBL]       DECIMAL (3)    NULL,
    [ITUDOS]       CHAR (1)       NULL,
    [ITMMIC]       CHAR (1)       NULL,
    [ITBALW]       CHAR (1)       NULL,
    [ITCNVT]       DECIMAL (4)    NULL,
    [ITCVNB]       DECIMAL (6)    NULL,
    [ITCOMM]       CHAR (1)       NULL,
    [ITVQDE]       CHAR (1)       NULL,
    [ITOV12]       CHAR (1)       NULL,
    [ITOV1]        CHAR (1)       NULL,
    [ITLRQE]       CHAR (1)       NULL,
    [ITFSIN]       DECIMAL (6)    NULL,
    [ITSSIN]       DECIMAL (6)    NULL,
    [ITRPSI]       DECIMAL (6)    NULL,
    [ITPUML]       DECIMAL (5)    NULL,
    [ITVQD]        CHAR (1)       NULL,
    [ITGLIN]       CHAR (24)      NULL,
    [ITGLSL]       CHAR (24)      NULL,
    [ITGLCS]       CHAR (24)      NULL,
    [ITSHGT]       DECIMAL (6, 3) NULL,
    [ITSLGN]       DECIMAL (6, 3) NULL,
    [ITSWTH]       DECIMAL (6, 3) NULL,
    [ITSWGT]       DECIMAL (5, 2) NULL,
    [ITPHGT]       DECIMAL (6, 3) NULL,
    [ITPLGN]       DECIMAL (6, 3) NULL,
    [ITPWTH]       DECIMAL (6, 3) NULL,
    [ITPWGT]       DECIMAL (5, 2) NULL,
    [ITMNRC]       CHAR (2)       NULL,
    [ITREFG]       CHAR (1)       NULL,
    [ITMSPH]       CHAR (2)       NULL,
    [ITWLFS]       CHAR (12)      NULL,
    [ITWLFN]       CHAR (60)      NULL,
    [ITMDS1]       CHAR (12)      NULL,
    [ITMDN1]       CHAR (60)      NULL,
    [ITMCDP]       CHAR (42)      NULL,
    [ITMNDC]       CHAR (12)      NULL,
    [ITNDCI]       CHAR (12)      NULL,
    [ITNDCP]       CHAR (12)      NULL,
    [ITNHRC]       CHAR (12)      NULL,
    [ITMUPC]       CHAR (12)      NULL,
    [ITUPCI]       CHAR (12)      NULL,
    [ITUPCP]       CHAR (12)      NULL,
    [ITMSCN]       CHAR (40)      NULL,
    [ITSCNI]       CHAR (40)      NULL,
    [ITSCNP]       CHAR (40)      NULL,
    [ITRX]         CHAR (1)       NULL,
    [ITRXDS]       CHAR (60)      NULL,
    [ITREST]       CHAR (9)       NULL,
    [ITSPLT]       CHAR (1)       NULL,
    [ITMSTK]       CHAR (1)       NULL,
    [ITSUOM]       CHAR (2)       NULL,
    [ITSMPK]       DECIMAL (6)    NULL,
    [ITPUOM]       CHAR (2)       NULL,
    [ITSINP]       DECIMAL (5)    NULL,
    [ITMUOM]       CHAR (2)       NULL,
    [ITSINM]       DECIMAL (5)    NULL,
    [ITMOQ]        DECIMAL (5)    NULL,
    [ITPMPQ]       DECIMAL (7)    NULL,
    [ITLOTC]       CHAR (1)       NULL,
    [ITRPLC]       DECIMAL (7, 2) NULL,
    [ITRPLP]       DECIMAL (7, 2) NULL,
    [ITAVWC]       DECIMAL (7, 2) NULL,
    [ITNETP]       DECIMAL (7, 2) NULL,
    [ITAWP]        CHAR (35)      NULL,
    [ITMNPQ]       CHAR (20)      NULL,
    [ITNBC]        CHAR (5)       NULL,
    [ITNSC]        CHAR (10)      NULL,
    [ITSRP]        DECIMAL (7, 2) NULL,
    [ITSTTX]       CHAR (99)      NULL,
    [ITMTCS]       DECIMAL (7, 2) NULL,
    [ITLBCS]       DECIMAL (7, 2) NULL,
    [ITFBCS]       DECIMAL (7, 2) NULL,
    [ITVBCS]       DECIMAL (7, 2) NULL,
    [ITICCS]       DECIMAL (7, 2) NULL,
    [ITSPPM]       CHAR (1)       NULL,
    [ITPCST]       DECIMAL (7, 2) NULL,
    [ITPSLP]       DECIMAL (7, 2) NULL,
    [ITPSDT]       DECIMAL (7)    NULL,
    [ITPEDT]       DECIMAL (7)    NULL,
    [ITPRDT]       DECIMAL (7)    NULL,
    [ITPALW]       DECIMAL (7, 2) NULL,
    [ITPAMQ]       DECIMAL (3)    NULL,
    [ITPASD]       DECIMAL (7)    NULL,
    [ITPAED]       DECIMAL (7)    NULL,
    [ITPDPC]       DECIMAL (4, 2) NULL,
    [ITPQFR]       DECIMAL (2)    NULL,
    [ITPQTY]       DECIMAL (4)    NULL,
    [ITSPCD]       DECIMAL (7)    NULL,
    [ITLPOD]       DECIMAL (7)    NULL,
    [ITLRCD]       DECIMAL (7)    NULL,
    [ITLSAD]       DECIMAL (7)    NULL,
    [ITLADT]       DECIMAL (7)    NULL,
    [ITGNCD]       CHAR (30)      NULL,
    [ITGNPI]       CHAR (1)       NULL,
    [ITGNTC]       CHAR (2)       NULL,
    [ITBARC]       CHAR (1)       NULL,
    [ITPBCL]       CHAR (1)       NULL,
    [ITBCLT]       CHAR (1)       NULL,
    [ITMGRM]       DECIMAL (7)    NULL,
    [FPITMMAS_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FPITMMAS_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FPITMMAS] PRIMARY KEY NONCLUSTERED ([FPITMMAS_key] ASC)
);


GO
CREATE CLUSTERED INDEX [FPITMMAS_IX_clustered]
    ON [dbo].[FPITMMAS]([ITMNUM] ASC);

