CREATE TABLE [dbo].[FPORDHDR] (
    [ORDNUM]       DECIMAL (8)    NULL,
    [ORDSTA]       CHAR (1)       NULL,
    [ORCRST]       CHAR (1)       NULL,
    [ORDSRC]       CHAR (2)       NULL,
    [ORDCNF]       DECIMAL (7)    NULL,
    [ORDTYP]       CHAR (1)       NULL,
    [ORDBIL]       DECIMAL (6)    NULL,
    [ORDSHT]       DECIMAL (6)    NULL,
    [ORSHNA]       CHAR (30)      NULL,
    [ORSHED]       CHAR (30)      NULL,
    [ORSSTR]       CHAR (30)      NULL,
    [ORSTWN]       CHAR (20)      NULL,
    [ORSSTA]       CHAR (2)       NULL,
    [ORSZIP]       CHAR (9)       NULL,
    [ORSCNT]       CHAR (10)      NULL,
    [ORDRUT]       DECIMAL (3)    NULL,
    [ORDRSQ]       DECIMAL (3)    NULL,
    [ORDPON]       CHAR (25)      NULL,
    [ORDCTP]       DECIMAL (4)    NULL,
    [ORDSLM]       DECIMAL (4)    NULL,
    [ORSLSD]       DECIMAL (1)    NULL,
    [ORDAMT]       DECIMAL (9, 2) NULL,
    [ORDLIN]       DECIMAL (4)    NULL,
    [ORLNFL]       DECIMAL (4)    NULL,
    [ORLNBK]       DECIMAL (4)    NULL,
    [ORDUNI]       DECIMAL (7)    NULL,
    [ORDUNS]       DECIMAL (7)    NULL,
    [ORDSDT]       DECIMAL (7)    NULL,
    [ORDSHP]       DECIMAL (2)    NULL,
    [ORDDAT]       DECIMAL (7)    NULL,
    [ORDTIM]       DECIMAL (6)    NULL,
    [ORDADT]       DECIMAL (7)    NULL,
    [ORDFDT]       DECIMAL (7)    NULL,
    [ORASDT]       DECIMAL (7)    NULL,
    [ORDPDT]       DECIMAL (7)    NULL,
    [ORDIDC]       DECIMAL (6)    NULL,
    [ORCARC]       CHAR (2)       NULL,
    [ORCARN]       CHAR (30)      NULL,
    [ORDIN1]       CHAR (30)      NULL,
    [ORDIN2]       CHAR (30)      NULL,
    [ORDIN3]       CHAR (30)      NULL,
    [ORDMSI]       CHAR (1)       NULL,
    [ORDLBF]       CHAR (1)       NULL,
    [ORDLAB]       DECIMAL (4)    NULL,
    [ORBLNK]       CHAR (9)       NULL,
    [OROGWS]       DECIMAL (2)    NULL,
    [ORORVB]       DECIMAL (1)    NULL,
    [ORHOSH]       CHAR (1)       NULL,
    [ORBOOV]       CHAR (1)       NULL,
    [ORCOD]        CHAR (1)       NULL,
    [ORTRMS]       CHAR (2)       NULL,
    [ORPLBY]       CHAR (20)      NULL,
    [ORDMFD]       CHAR (1)       NULL,
    [ORSPLT]       CHAR (1)       NULL,
    [ORBEST]       CHAR (1)       NULL,
    [ORSPDM]       CHAR (1)       NULL,
    [ORSTYP]       CHAR (1)       NULL,
    [ORVAIN]       CHAR (1)       NULL,
    [ORCODP]       CHAR (1)       NULL,
    [ORADD$]       DECIMAL (7, 2) NULL,
    [ORBILL]       CHAR (1)       NULL,
    [ORBLCS]       DECIMAL (9)    NULL,
    [ORINYN]       CHAR (1)       NULL,
    [ORBTYP]       CHAR (1)       NULL,
    [ORCNM]        CHAR (24)      NULL,
    [ORHLDA]       CHAR (1)       NULL,
    [ORDSAT]       CHAR (1)       NULL,
    [ORPREF]       CHAR (1)       NULL,
    [ORCDSP]       DECIMAL (3, 3) NULL,
    [ORBGRP]       CHAR (5)       NULL,
    [ORCHID]       CHAR (5)       NULL,
    [ORANOR]       CHAR (20)      NULL,
    [FPORDHDR_key] INT            IDENTITY (1, 1) NOT NULL,
    [load_date]    DATETIME       CONSTRAINT [DF_FPORDHDR_load_date] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FPORDHDR] PRIMARY KEY NONCLUSTERED ([FPORDHDR_key] ASC)
);


GO
CREATE CLUSTERED INDEX [FPORDHDR_IX_clustered]
    ON [dbo].[FPORDHDR]([ORDNUM] ASC, [ORDSTA] ASC, [ORDBIL] ASC, [ORDSHT] ASC);

