CREATE PROCEDURE [dbo].[linked_server_refresh]
AS
BEGIN
	SET NOCOUNT ON;

	RAISERROR (
	'Starting process....'
	,0
	,1
	)
	WITH NOWAIT;
	

	RAISERROR (
	'Insert into FLCUSSUB..'
	,0
	,1
	)
	WITH NOWAIT

	truncate table [dbo].[FLCUSSUB]

	INSERT INTO [dbo].[FLCUSSUB] ( CCNMBR, CCODED, CCGLSL, CCGLCS, CCSTYP, CCVAIN, CCCODP, CCBILL, CCBLCS, CCINYN, CCBTYP, CCRCNM, CCOFFP, CCODAY, CCOEXP, CCABCD, CCKYAC, CCVOLD, CCCYYN, CCCCGP, CCFORM, CCADDD, CCMNTD, CCEMAL, CCDP4N, [CCIMH$], CCBMEX, CCACPR )
	 EXEC('SELECT  CCNMBR,
            CCODED,
            CCGLSL,
            CCGLCS,
            CCSTYP,
            CCVAIN,
            CCCODP,
            CCBILL,
            CCBLCS,
            CCINYN,
            CCBTYP,
            CCRCNM,
            CCOFFP,
            CCODAY,
            CCOEXP,
            CCABCD,
            CCKYAC,
            CCVOLD,
            CCCYYN,
            CCCCGP,
            CCFORM,
            CCADDD,
            CCMNTD,
            CCEMAL,
            CCDP4N,
            CCIMH$,
            CCBMEX,
            CCACPR
    FROM    CIGFTEST.FLCUSSUB') AT TPS;


	RAISERROR (

	'Insert into FLITMSUB..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FLITMSUB;


	INSERT INTO dbo.FLITMSUB ( IINMBR, IIDGRT, IIMINO, IIHAZM, IISPYN, IISMFG, IIFORM, IILMTU, IILMTP, IIADSC, IIHZMX, IISHDT, IIOVCG, IIPLCT, IICNTP, IIDOSE, IIMDL, IIVCTX, IIFGEL, IIBDNM, IICCFQ, IICHFM, IIACFM, IIORET, IIMFCN, IISLBN, IIMNQT, IICNTY, IISDRT, IIRSRV, IIRGFM, IIONFM, IIWKEY, IIGTIN, IILNAM, IISPLM, IISPLA, IIMCRD, IITOPP, IIPCNM, IISPEC, IIIMS, IICONT, I@SPRT, IIOVRLMT, IIAITEM1, IIAITEM2, IIFLAG1, IIFLAG2, IIMDOH, IIPRLK, IICATG, IISEG1, IISEG2, IINORW )
	EXEC('SELECT  IINMBR,
            IIDGRT,
            IIMINO,
            IIHAZM,
            IISPYN,
            IISMFG,
            IIFORM,
            IILMTU,
            IILMTP,
            IIADSC,
            IIHZMX,
            IISHDT,
            IIOVCG,
            IIPLCT,
            IICNTP,
            IIDOSE,
            IIMDL,
            IIVCTX,
            IIFGEL,
            IIBDNM,
            IICCFQ,
            IICHFM,
            IIACFM,
            IIORET,
            IIMFCN,
            IISLBN,
            IIMNQT,
            IICNTY,
            IISDRT,
            IIRSRV,
            IIRGFM,
            IIONFM,
            IIWKEY,
            IIGTIN,
            IILNAM,
            IISPLM,
            IISPLA,
            IIMCRD,
            IITOPP,
            IIPCNM,
            IISPEC,
            IIIMS,
            IICONT,
            I@SPRT,
            IIOVRLMT,
            IIAITEM1,
            IIAITEM2,
            IIFLAG1,
            IIFLAG2,
            IIMDOH,
            IIPRLK,
            IICATG,
            IISEG1,
            IISEG2,
            IINORW
    FROM    CIGFTEST.FLITMSUB') AT TPS; ----CIGFTEST.FLITMSUB


	RAISERROR (
	'Insert into [FPCUSMAS]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPCUSMAS;
	INSERT INTO dbo.FPCUSMAS ( CNUMBR, CLNAME, CAHEAD, CSTRET, CCTOWN, CSTATE, CZIP, CSALSR, CSRNAM, CSRCTN, CSMAIL, CCTYCD, CCNTRY, CCONTY, CTERRY, CREGN, CSTUS, CCRSTS, CCHIER, CBILTO, CSLTX#, CSTEXP, CSINST, CSRRTN, CSARTL, CLPCD, CLPPCT, CLPDFT, CLDFTP, CLDFTA, CSPCD, CCPDSC, CPMCD, CSACST, CSCRLM, CSPORQ, CSDSAC, CSTXEM, CSBACK, CCOMDF, CSSPLT, CSISEQ, CSACCD, CSBLST, CSSPEC, CSBEST, CSMNDV, CSIVDP, CSCHDP, CSLSMN, CSCMDP, [CSADD$], CSTREG, CSREXP, CDEA#, CDEEXP, CSHIN#, CLAB1, CLAB2, CSTXT1, CSTXT2, CSTXT3, CSPHNA, CSPHNE, CSPHNN, CSFAXA, CSFAXE, CSFAXN, CSRCNM, CSRCEX, CSCHLD, CVLCTY, CSSTAX, CSLTX1, CSLTX2, CSAUTP, CSAUEX, CSPSPW, CSCAR#, CSPREF, CSLADT, CTYPE, CSBSTY, CSACTY, CSOMIT, CBONLY, C1IOD, CSPHRM, C1COD, CSSUB, CSRPCK, CSREST, CSDUPI, CSSHPL, CSPARS, CSPRCL, CARGL, CSCDS#, CSLBL#, CSOID#, CSROE#, CSSDS#, CREMIT, CSANL1, CSANL2, CPRAWP, CMSIFL, CMSISR, CSPCOC, CSPDOC, CSBLOC, CSSRX, CSSOTC, CSRXSL, CSOTSL, CSGNSB, CSGNPF, CSGNDS, CSBOMG, CSEDI1, CSEDI2, CSLSDT, CSOTSC, CSOTPD, CSRBTC, CSSPDM, CSEDII, CSEDIP, CSCONF, CSCFDT, CSMXLB, CSMGRM, CSSGRM )
	EXEC('SELECT  CNUMBR,
            CLNAME,
            CAHEAD,
            CSTRET,
            CCTOWN,
            CSTATE,
            CZIP,
            CSALSR,
            CSRNAM,
            CSRCTN,
            CSMAIL,
            CCTYCD,
            CCNTRY,
            CCONTY,
            CTERRY,
            CREGN,
            CSTUS,
            CCRSTS,
            CCHIER,
            CBILTO,
            CSLTX#,
            CSTEXP,
            CSINST,
            CSRRTN,
            CSARTL,
            CLPCD,
            CLPPCT,
            CLPDFT,
            CLDFTP,
            CLDFTA,
            CSPCD,
            CCPDSC,
            CPMCD,
            CSACST,
            CSCRLM,
            CSPORQ,
            CSDSAC,
            CSTXEM,
            CSBACK,
            CCOMDF,
            CSSPLT,
            CSISEQ,
            CSACCD,
            CSBLST,
            CSSPEC,
            CSBEST,
            CSMNDV,
            CSIVDP,
            CSCHDP,
            CSLSMN,
            CSCMDP,
            CSADD$,
            CSTREG,
            CSREXP,
            CDEA#,
            CDEEXP,
            CSHIN#,
            CLAB1,
            CLAB2,
            CSTXT1,
            CSTXT2,
            CSTXT3,
            CSPHNA,
            CSPHNE,
            CSPHNN,
            CSFAXA,
            CSFAXE,
            CSFAXN,
            CSRCNM,
            CSRCEX,
            CSCHLD,
            CVLCTY,
            CSSTAX,
            CSLTX1,
            CSLTX2,
            CSAUTP,
            CSAUEX,
            CSPSPW,
            CSCAR#,
            CSPREF,
            CSLADT,
            CTYPE,
            CSBSTY,
            CSACTY,
            CSOMIT,
            CBONLY,
            C1IOD,
            CSPHRM,
            C1COD,
            CSSUB,
            CSRPCK,
            CSREST,
            CSDUPI,
            CSSHPL,
            CSPARS,
            CSPRCL,
            CARGL,
            CSCDS#,
            CSLBL#,
            CSOID#,
            CSROE#,
            CSSDS#,
            CREMIT,
            CSANL1,
            CSANL2,
            CPRAWP,
            CMSIFL,
            CMSISR,
            CSPCOC,
            CSPDOC,
            CSBLOC,
            CSSRX,
            CSSOTC,
            CSRXSL,
            CSOTSL,
            CSGNSB,
            CSGNPF,
            CSGNDS,
            CSBOMG,
            CSEDI1,
            CSEDI2,
            CSLSDT,
            CSOTSC,
            CSOTPD,
            CSRBTC,
            CSSPDM,
            CSEDII,
            CSEDIP,
            CSCONF,
            CSCFDT,
            CSMXLB,
            CSMGRM,
            CSSGRM
    FROM FPCUSMAS') AT TPS;

	RAISERROR (
	'Insert into [FPCUSSB2]..'
	,0
	,1
	)
	WITH NOWAIT

	TRUNCATE TABLE dbo.FPCUSSB2;
	INSERT INTO dbo.FPCUSSB2 ( C2NMBR, C2SHWS, C2SHW2, C2SHW3, C2TCLS, C2BGRP, C2BGID, C2CHID, C2CSID, C2SATD, C2MEID, C2TERR, C2PDEC, C2PSLS, C2ADSC, C2VIP#, C2SISC, C2ABC, C2PDSC, C2AFFL, C2DOVR, C2SOVR, C2SCPD, C2SPCR, C2EDG1, C2EDG2, C2NAME, C2OTCS, C2REBT, C2FAXS, C2MFOP, C2MFCL, C2SAOP, C2SACL, C2APH1, C2APH2, C2MDLO, C2FRTP, C2CATG, C2CDSC, C2CPDY, C2FPED, C2FGVL, C2FGPC, C2RMID, C2HAY#, C2DEA#, C2DEEX, C2RBCK, C2RCAC, C2BYCR, C2TCLT, C2QTDS, C2FXSC, C2PVID, C2340B, C2GPO, C2INCC, C2ISAC, C2EXAC, C2PDAM, C2NPI, C2GLN, C2PRAS, C2ACSF, C2CTCL, C2QEST, C2QDAT, C2FXSD, C2RFXA, C2RFXE, C2RFXN, C2STRG, C2SREX, C2SITC, C2WEBST, C2CTFG, C2CTDT, C2DSFG, C2DSDT, C2STYP, C2OLDT, C2SHC1, C2SHC2, C2SHC3, C2RCEM, C2RCPF, C2DTE1, C2DTE3, C21BK1, C21BK2, C21BK3, C22BK1, C22BK2, C22BK3, C23BK1, C23BK2, C23BK3, C24BK1, C24BK2, C24BK3, C26NM1, C26NM2, C26NM3, C2FID )
	EXEC('SELECT  C2NMBR,
            C2SHWS,
            C2SHW2,
            C2SHW3,
            C2TCLS,
            C2BGRP,
            C2BGID,
            C2CHID,
            C2CSID,
            C2SATD,
            C2MEID,
            C2TERR,
            C2PDEC,
            C2PSLS,
            C2ADSC,
            C2VIP#,
            C2SISC,
            C2ABC,
            C2PDSC,
            C2AFFL,
            C2DOVR,
            C2SOVR,
            C2SCPD,
            C2SPCR,
            C2EDG1,
            C2EDG2,
            C2NAME,
            C2OTCS,
            C2REBT,
            C2FAXS,
            C2MFOP,
            C2MFCL,
            C2SAOP,
            C2SACL,
            C2APH1,
            C2APH2,
            C2MDLO,
            C2FRTP,
            C2CATG,
            C2CDSC,
            C2CPDY,
            C2FPED,
            C2FGVL,
            C2FGPC,
            C2RMID,
            C2HAY#,
            C2DEA#,
            C2DEEX,
            C2RBCK,
            C2RCAC,
            C2BYCR,
            C2TCLT,
            C2QTDS,
            C2FXSC,
            C2PVID,
            C2340B,
            C2GPO,
            C2INCC,
            C2ISAC,
            C2EXAC,
            C2PDAM,
            C2NPI,
            C2GLN,
            C2PRAS,
            C2ACSF,
            C2CTCL,
            C2QEST,
            C2QDAT,
            C2FXSD,
            C2RFXA,
            C2RFXE,
            C2RFXN,
            C2STRG,
            C2SREX,
            C2SITC,
            C2WEBST,
            C2CTFG,
            C2CTDT,
            C2DSFG,
            C2DSDT,
            C2STYP,
            C2OLDT,
            C2SHC1,
            C2SHC2,
            C2SHC3,
            C2RCEM,
            C2RCPF,
            C2DTE1,
            C2DTE3,
            C21BK1,
            C21BK2,
            C21BK3,
            C22BK1,
            C22BK2,
            C22BK3,
            C23BK1,
            C23BK2,
            C23BK3,
            C24BK1,
            C24BK2,
            C24BK3,
            C26NM1,
            C26NM2,
            C26NM3,
            C2FID
    FROM    FPCUSSB2') AT TPS;

	RAISERROR (
	'Insert into [FPITMBAL]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPITMBAL
	INSERT INTO dbo.FPITMBAL ( IBITEM, IBWHSE, IBBUYR, IBBYRC, IBPICY, IBCULI, IBQHAW, IBQHAV, IBQHRS, IBQHSP, IBQMIP, IBQBAK, IBQONO, IBQTRI, IBQTRO, IBCMAV, IBCMRS, IBCMBK, IBTCMA, IBTCMR, IBQTRV, IBQCRV, IBQORV, IBQASC, IBSQOP, IBQOHB, IBQOHA, IBLRDT, IBNRDT, IBLSDT, IBLCDT, IBLPDT, IBLTDT, IBFPDT, IBFCDT, IBLIDT, IBINVT, IBFAST, IBAWC, [IBLFO$], IBLFOD, IBREOP, IBEOQ, IBABCC, IBSVCL, IBBUYF, IBSFST, IBPRDM, IBLSWP, IBLTDM, IBLTP, IBPRLT, IBABLD, IBLTLD, IBPDLD, IBRPLD, IBLSLD )
	EXEC('SELECT  IBITEM,
            IBWHSE,
            IBBUYR,
            IBBYRC,
            IBPICY,
            IBCULI,
            IBQHAW,
            IBQHAV,
            IBQHRS,
            IBQHSP,
            IBQMIP,
            IBQBAK,
            IBQONO,
            IBQTRI,
            IBQTRO,
            IBCMAV,
            IBCMRS,
            IBCMBK,
            IBTCMA,
            IBTCMR,
            IBQTRV,
            IBQCRV,
            IBQORV,
            IBQASC,
            IBSQOP,
            IBQOHB,
            IBQOHA,
            IBLRDT,
            IBNRDT,
            IBLSDT,
            IBLCDT,
            IBLPDT,
            IBLTDT,
            IBFPDT,
            IBFCDT,
            IBLIDT,
            IBINVT,
            IBFAST,
            IBAWC,
            IBLFO$,
            IBLFOD,
            IBREOP,
            IBEOQ,
            IBABCC,
            IBSVCL,
            IBBUYF,
            IBSFST,
            IBPRDM,
            IBLSWP,
            IBLTDM,
            IBLTP,
            IBPRLT,
            IBABLD,
            IBLTLD,
            IBPDLD,
            IBRPLD,
            IBLSLD
    FROM    FPITMBAL') AT TPS;

	RAISERROR (
	'Insert into [FPITMBRS]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPITMBRS;
	INSERT INTO dbo.FPITMBRS ( IRITEM, IRWHSE, IRCTYP, IRQHRS, IRONLY, IRBYLM )
	EXEC('    SELECT  IRITEM,
            IRWHSE,
            IRCTYP,
            IRQHRS,
            IRONLY,
            IRBYLM
    FROM    FPITMBRS') AT TPS;

	RAISERROR (
	'Insert into [FPITMMAS]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPITMMAS;
	INSERT INTO dbo.FPITMMAS ( ITMNUM, ITSTAT, ITDLD, ITINVT, ITINVC, ITSPCG, ITDESC, ITSDES, ITQUAL, ITQULD, ITGNRC, ITGNSR, ITSIZE, ITFORM, ITFLNE, ITFLSN, ITVNDN, ITVSUF, ITVNSO, ITVNSR, ITYNDC, ITNWTT, ITNLBL, ITUDOS, ITMMIC, ITBALW, ITCNVT, ITCVNB, ITCOMM, ITVQDE, ITOV12, ITOV1, ITLRQE, ITFSIN, ITSSIN, ITRPSI, ITPUML, ITVQD, ITGLIN, ITGLSL, ITGLCS, ITSHGT, ITSLGN, ITSWTH, ITSWGT, ITPHGT, ITPLGN, ITPWTH, ITPWGT, ITMNRC, ITREFG, ITMSPH, ITWLFS, ITWLFN, ITMDS1, ITMDN1, ITMCDP, ITMNDC, ITNDCI, ITNDCP, ITNHRC, ITMUPC, ITUPCI, ITUPCP, ITMSCN, ITSCNI, ITSCNP, ITRX, ITRXDS, ITREST, ITSPLT, ITMSTK, ITSUOM, ITSMPK, ITPUOM, ITSINP, ITMUOM, ITSINM, ITMOQ, ITPMPQ, ITLOTC, ITRPLC, ITRPLP, ITAVWC, ITNETP, ITAWP, ITMNPQ, ITNBC, ITNSC, ITSRP, ITSTTX, ITMTCS, ITLBCS, ITFBCS, ITVBCS, ITICCS, ITSPPM, ITPCST, ITPSLP, ITPSDT, ITPEDT, ITPRDT, ITPALW, ITPAMQ, ITPASD, ITPAED, ITPDPC, ITPQFR, ITPQTY, ITSPCD, ITLPOD, ITLRCD, ITLSAD, ITLADT, ITGNCD, ITGNPI, ITGNTC, ITBARC, ITPBCL, ITBCLT, ITMGRM )
	EXEC('SELECT  ITMNUM,
            ITSTAT,
            ITDLD,
            ITINVT,
            ITINVC,
            ITSPCG,
            ITDESC,
            ITSDES,
            ITQUAL,
            ITQULD,
            ITGNRC,
            ITGNSR,
            ITSIZE,
            ITFORM,
            ITFLNE,
            ITFLSN,
            ITVNDN,
            ITVSUF,
            ITVNSO,
            ITVNSR,
            ITYNDC,
            ITNWTT,
            ITNLBL,
            ITUDOS,
            ITMMIC,
            ITBALW,
            ITCNVT,
            ITCVNB,
            ITCOMM,
            ITVQDE,
            ITOV12,
            ITOV1,
            ITLRQE,
            ITFSIN,
            ITSSIN,
            ITRPSI,
            ITPUML,
            ITVQD,
            ITGLIN,
            ITGLSL,
            ITGLCS,
            ITSHGT,
            ITSLGN,
            ITSWTH,
            ITSWGT,
            ITPHGT,
            ITPLGN,
            ITPWTH,
            ITPWGT,
            ITMNRC,
            ITREFG,
            ITMSPH,
            ITWLFS,
            ITWLFN,
            ITMDS1,
            ITMDN1,
            ITMCDP,
            ITMNDC,
            ITNDCI,
            ITNDCP,
            ITNHRC,
            ITMUPC,
            ITUPCI,
            ITUPCP,
            ITMSCN,
            ITSCNI,
            ITSCNP,
            ITRX,
            ITRXDS,
            ITREST,
            ITSPLT,
            ITMSTK,
            ITSUOM,
            ITSMPK,
            ITPUOM,
            ITSINP,
            ITMUOM,
            ITSINM,
            ITMOQ,
            ITPMPQ,
            ITLOTC,
            ITRPLC,
            ITRPLP,
            ITAVWC,
            ITNETP,
            ITAWP,
            ITMNPQ,
            ITNBC,
            ITNSC,
            ITSRP,
            ITSTTX,
            ITMTCS,
            ITLBCS,
            ITFBCS,
            ITVBCS,
            ITICCS,
            ITSPPM,
            ITPCST,
            ITPSLP,
            ITPSDT,
            ITPEDT,
            ITPRDT,
            ITPALW,
            ITPAMQ,
            ITPASD,
            ITPAED,
            ITPDPC,
            ITPQFR,
            ITPQTY,
            ITSPCD,
            ITLPOD,
            ITLRCD,
            ITLSAD,
            ITLADT,
            ITGNCD,
            ITGNPI,
            ITGNTC,
            ITBARC,
            ITPBCL,
            ITBCLT,
            ITMGRM
    FROM    FPITMMAS') AT TPS;

	RAISERROR (
	'Insert into [FPLOCMST]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPLOCMST;
	INSERT INTO dbo.FPLOCMST ( LCWHSE, LCADD1, LCADD2, LCCITY, LCSTAT, LCZIP, LCPHNA, LCPHNE, LCPHNN, LCADDT, LCMNDT, LCMSG1, LCMSG2, LCMSG3, LCMSG4, LCMSG5, LCMSG6, LCWORD, LCDDWH, LCDDCC, LCRECA, LCCRDA, LCSCRA, LCRTVA, LCPVRA, LCMIPA, LCBYHA, LCISTA, LCPAGE, LCABCD, LCOINT, LCOINS, LCOHAN, LCDEA#, LCFDA#, LCHIN#, LCDSVC, LCMONW, LCTRNI, LCTRNO, LCPAR#, LCSQTO, LCCPER, LCCVR1, LCCOP1, LCCVR2, LCCOP2, LCCVR3, LCCCAL, LCSPER, LCSVR1, LCSOP1, LCSVR2, LCSOP2, LCSVR3, LCSCAL, LCARCO, LCARIN, LCARRP, LCARDM, LCCBCO, LCCBDR, LCCBCR, LCPMDR, LCPMCR, LCRBCO, LCRBDR, LCRBCR, LCAPCO, LCTYPE, LCCURR, LCCRTY, LCDPTC, LCVRAC, LCCPLS, LCCMNS, LCAMSC, LCAMS2, LCAMS3, LCAMS4, LCAEDS, LCDMRV, LCCPAG, LCAIEC, LCCNFM, LCDPOE, LCAMVR, LCAMVC, LCAMVM, LCVRPA, LCVRNA, LCMXLB, LCBARC, LCEDIN, LCEDIA, LCEDIC, LCEDIS, LCEDIZ, LCVRGL, LCRBSL, LCRBAC, LCRBAR, LCPMAR, LCRPFM, LCICOS, LCCOSI, LCTPID, LCALO#, LCAHI#, LCALU#, LCACON, LCNDCV, LCSSGL, LCPCD, LCPDSC, LCBLST, LCPCOC, LCPDOC, LCBLOC, LCIDSP, LCMNHL, LCSPOM, LCLMTU, LCLMTP, LCBMIN )
	EXEC('SELECT  LCWHSE,
            LCADD1,
            LCADD2,
            LCCITY,
            LCSTAT,
            LCZIP,
            LCPHNA,
            LCPHNE,
            LCPHNN,
            LCADDT,
            LCMNDT,
            LCMSG1,
            LCMSG2,
            LCMSG3,
            LCMSG4,
            LCMSG5,
            LCMSG6,
            LCWORD,
            LCDDWH,
            LCDDCC,
            LCRECA,
            LCCRDA,
            LCSCRA,
            LCRTVA,
            LCPVRA,
            LCMIPA,
            LCBYHA,
            LCISTA,
            LCPAGE,
            LCABCD,
            LCOINT,
            LCOINS,
            LCOHAN,
            LCDEA#,
            LCFDA#,
            LCHIN#,
            LCDSVC,
            LCMONW,
            LCTRNI,
            LCTRNO,
            LCPAR#,
            LCSQTO,
            LCCPER,
            LCCVR1,
            LCCOP1,
            LCCVR2,
            LCCOP2,
            LCCVR3,
            LCCCAL,
            LCSPER,
            LCSVR1,
            LCSOP1,
            LCSVR2,
            LCSOP2,
            LCSVR3,
            LCSCAL,
            LCARCO,
            LCARIN,
            LCARRP,
            LCARDM,
            LCCBCO,
            LCCBDR,
            LCCBCR,
            LCPMDR,
            LCPMCR,
            LCRBCO,
            LCRBDR,
            LCRBCR,
            LCAPCO,
            LCTYPE,
            LCCURR,
            LCCRTY,
            LCDPTC,
            LCVRAC,
            LCCPLS,
            LCCMNS,
            LCAMSC,
            LCAMS2,
            LCAMS3,
            LCAMS4,
            LCAEDS,
            LCDMRV,
            LCCPAG,
            LCAIEC,
            LCCNFM,
            LCDPOE,
            LCAMVR,
            LCAMVC,
            LCAMVM,
            LCVRPA,
            LCVRNA,
            LCMXLB,
            LCBARC,
            LCEDIN,
            LCEDIA,
            LCEDIC,
            LCEDIS,
            LCEDIZ,
            LCVRGL,
            LCRBSL,
            LCRBAC,
            LCRBAR,
            LCPMAR,
            LCRPFM,
            LCICOS,
            LCCOSI,
            LCTPID,
            LCALO#,
            LCAHI#,
            LCALU#,
            LCACON,
            LCNDCV,
            LCSSGL,
            LCPCD,
            LCPDSC,
            LCBLST,
            LCPCOC,
            LCPDOC,
            LCBLOC,
            LCIDSP,
            LCMNHL,
            LCSPOM,
            LCLMTU,
            LCLMTP,
            LCBMIN
    FROM    FPLOCMST') AT TPS;

	RAISERROR (
	'Insert into [FPLOCSUB]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPLOCSUB;
	INSERT INTO dbo.FPLOCSUB ( LSWHSE, LSDAY, LSDATE, LSTIME, LSROLWHS )
    EXEC('SELECT  LSWHSE,
            LSDAY,
            LSDATE,
            LSTIME,
            LSROLWHS
    FROM    FPLOCSUB') AT TPS;

	RAISERROR (
	'Inserting into [FPPGMDTA]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPPGMDTA;
	INSERT INTO dbo.FPPGMDTA ( PDPROGRAM, PDFORMAT, PDSEQ, PDDATA )
	EXEC('SELECT  PDPROGRAM,
            PDFORMAT,
            PDSEQ,
            PDDATA
    FROM    AGID06USR.FPPGMDTA') AT TPS;

	RAISERROR (
	'Inserting into [FPSUBITM]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPSUBITM;
	INSERT INTO dbo.FPSUBITM ( SITYPE, SICUST, SIITEM, SISEQ, SISITM, SIITMR, SIPROR, SISTAT, SIADAT, SIMDAT, SIMTIM, SIMUSR )
	EXEC('SELECT  SITYPE,
            SICUST,
            SIITEM,
            SISEQ,
            SISITM,
            SIITMR,
            SIPROR,
            SISTAT,
            SIADAT,
            SIMDAT,
            SIMTIM,
            SIMUSR
    FROM    FPSUBITM') AT TPS;

	RAISERROR (
	'Inserting into [FPWHLDTL]..'
	,0
	,1
	)
	WITH NOWAIT
	TRUNCATE TABLE dbo.FPWHLDTL;
	INSERT INTO dbo.FPWHLDTL ( WDLOC, WDZONE, WDAISL, WDBAY, WDTIER, WDBIN, WDITEM, WDDATE, WDTIME, WDQTYA, WDATYP, WDDSPY, WDOLOC, WDSTAT, WDUSET, WDRTYP, WDVNDN, WDPO#, WDLOT, WDEXPD, WDCRUP, WDVEXP )
	EXEC('SELECT  WDLOC,
            WDZONE,
            WDAISL,
            WDBAY,
            WDTIER,
            WDBIN,
            WDITEM,
            WDDATE,
            WDTIME,
            WDQTYA,
            WDATYP,
            WDDSPY,
            WDOLOC,
            WDSTAT,
            WDUSET,
            WDRTYP,
            WDVNDN,
            WDPO#,
            WDLOT,
            WDEXPD,
            WDCRUP,
            WDVEXP
    FROM    FPWHLDTL') AT TPS;

	RAISERROR (
	'Job complete...'
	,0
	,1
	)
	WITH NOWAIT;

	exec [dbo].[materialize_item_balances]
	
END;
